version: "3.8"

services:
  server:
    image: ghcr.io/divyam234/drive
    restart: always
    container_name: drive
    volumes:
      - ./drive.db:/app/drive.db:rw
    env_file: drive.env
    ports:
      - 8080:8080
