version: "3.8"

services:
  server:
    image: ghcr.io/divyam234/drive/server
    restart: always
    container_name: drive
    volumes:
      - ./drive.db:/app/drive.db:rw
    env_file: drive.env
    ports:
      - 8080:8080
  db:
    image: postgres:15
    container_name: drive_db
    restart: always
    environment:
      - POSTGRES_USER=drive
      - POSTGRES_PASSWORD=secret
    volumes:
      - drive_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "drive"]
      interval: 10s
      start_period: 30s

volumes:
  drive_db:
  